color_1:
  type: string
  default: ""
  description:
    en: "font color for this group. Use Discourse theme color variables, color names or hexadecimal codes."

group_1:
  type: list
  list_type: group
  default: ""
  description:
    en: "Use font color for these groups only."
